Repository SVijayB/Quizzatron, pull requests merged in 2025-03, with the labels that each got.

#24 Setup wsgi backend server for deployment
  .env.example
  .github/workflows/ci-format.yml
  .github/workflows/ci-test.yml
  api/app.py
  docs/technology_review/demo_scripts/gemini_demo.py
  docs/technology_review/demo_scripts/icrawler_demo.py
  docs/technology_review/demo_scripts/pypdf_demo.py
  frontend/src/pages/Index.tsx
  requirements.txt
  tests/conftest.py
  tests/test_app.py
  wsgi.py
Labels: enhancement

#26 Commented out cleanup module, to enable parallel quizzing
  api/utils/quiz_gen.py
Labels: enhancement

#27 Linting completed
  .github/workflows/ci-format.yml
  api/__init__.py
  api/app.py
  api/routes/__init__.py
  api/routes/quiz_gen_api.py
  api/services/quiz_gen_service.py
  api/utils/extract_img.py
  api/utils/quiz_gen.py
  api/utils/validate_output.py
  docs/technology_review/demo_scripts/gemini_demo.py
  docs/technology_review/demo_scripts/icrawler_demo.py
  docs/technology_review/demo_scripts/pypdf_demo.py
  requirements.txt
  scripts/cli.py
  scripts/quiz_gen.py
  tests/conftest.py
  tests/test_app.py
  tests/test_extract_img.py
  tests/test_quiz_gen_api.py
  tests/test_quiz_gen_service.py
  tests/test_quiz_gen_util.py
  tests/test_validate_output.py
  wsgi.py
Labels: documentation, enhancement

#28 Hotfix: Fixed issue with frontend not rendering
  api/services/quiz_gen_service.py
Labels: bug

#31 Complete README.md overhaul - Added contributors and new installation steps
  .all-contributorsrc
  .env.example
  README.md
  assets/ss-1.png
Labels: documentation
